elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch
  image: unicell/elasticsearch:latest
kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  image: unicell/kibana:latest
logstash:
  extends:
    file: docker-compose-common.yml
    service: logstash
  links:
    - elasticsearch:elasticsearch
logspout:
  extends:
    file: docker-compose-common.yml
    service: logspout
  image: unicell/logspout:v3-master
  links:
    - logstash:logstash
  command: syslog://logstash:5000
cadvisor:
  extends:
    file: docker-compose-common.yml
    service: cadvisor
