elasticsearch:
  extends:
    file: common.yml
    service: elasticsearch
kibana:
  extends:
    file: common.yml
    service: kibana
  links:
    - elasticsearch
logstash:
  extends:
    file: common.yml
    service: logstash
  links:
    - elasticsearch
logspout:
  extends:
    file: common.yml
    service: logspout
  environment:
    DEBUG: true
  links:
    - logstash
  command: syslog://logstash:5000
cadvisor:
  extends:
    file: common.yml
    service: cadvisor
